---
locale: es
tags:
- funciones
layout: input_right
editor: code
type: problem
extra_visible: false
teacher_info: Leandro Batlle
manual_evaluation: false
progressive_expectations: false
choices: []
name: Funciones que funcionan
