---
locale: es
tags:
- funciones
- funciones_invocación
- funciones_encabezado
- primitivas_input
- primitivas_int
layout: input_right
editor: code
type: problem
extra_visible: false
teacher_info: Leandro Batlle
manual_evaluation: false
choices: []
name: Jugamos a leer la mente
